name: Digital Ocean CI/CD
on:
  push:
    branches: [master]
  
  
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: usr/share/nginx/html
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
  
