name: Digital Ocean CI/CD
on:
  push:
    branches: [master]
  
  
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Github Ci/CD
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        source: /
        target: "/nodex"
    - run: npm install
      name: Finalize CI/CD
  
