name: Digital Ocean CI/CD
on:
  push:
    branches: [master]
  
  
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Compile into TAR
      run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: ${{secrets.PORT}}
        timeout: 5m
        command_timeout: 20m
        source: "deploy.tar"
        target: "~/nodex"
    - run: npm install
      name: Finalize CI/CD
  
