name: Digital Ocean CI/CD
on:
  push:
    branches: [master]
  
  
jobs:
  flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jjst/action-digitalocean-deploy-app@v2
      with:
        token: 501a25886a810310ab987534f266ac9251e6d73094fe820097f6dc90cc9a38dc
      name: Deploy to DigitalOcean
    - run: npm install
      name: Build and Run Backend
    
  
